version: "3.3"
services:
  nginx:
    image: nginx:1.12.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot/:/var/www/html/:rw
      - ./logs/wwwlogs/:/var/log/wwwlogs/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "PHYSICAL_IP:172.16.30.165"
    networks:
      - net-nginx
      - net-node
    depends_on:
      - node
      - redis
    dns:
      - 8.8.8.8
      - 9.9.9.9

  node:
    build: ./build/node/
    container_name: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./wwwroot/:/home/node/app:rw
    extra_hosts:
      - "PHYSICAL_IP:172.16.30.165"
    networks:
      - net-node
      - net-mysql
      - net-redis
    ports:
      - "7012:7012"
      - "8080:8080"

  mysql:
    image: mysql:5.6.40
    container_name: mysql
    ports:
      - "3066:3066"
    volumes:
      - ./conf/mysql/etc/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./db/mysql/database/:/var/lib/mysql/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  
  redis:
    image: redis:4.0
    container_name: redis
    networks:
      - net-redis
    # 全局服务是在每个节点上运行一个任务的服务。没有预先指定的任务数量。每次向swarm添加节点时，orchestrator都会创建一个任务，并且调度程序会将任务分配给新节点。
    # 适用于全局服务的良好候选者是监视代理程序，防病毒扫描程序或您希望在群集中的每个节点上运行的其他类型的容器。
    # see https://docs.docker-cn.com/engine/swarm/how-swarm-mode-works/services/#replicated-and-global-services
    # deploy:                 # 部署配置
    #   mode: replicated      # 部署模式  replicated|global (复制和全局服务) 默认: replicated
    #   replicas: 1           # 指定数量的容器
    #   # update_config:        
    #   #   parallelism: 2      # 一次更新的容器数
    #   #   delay: 10s          # 更新延迟
    #   restart_policy:       # 重启策略
    #     condition: on-failure   # 当失败的时候重启
    #   placement:            # 部署位置
    #     constraints:        
    #       - node.role == manager   # 部署的节点为管理节点
    #   # resources:            # 容器资源配置
    #   #   limits:
    #   #     cpus: '0.1'      # 使用 cpu 10%
    #   #     memory: 50M      # 内存最大M
    #   #   reservations:      # 保留资源
    #   #     cpus: '0.01'     # 5%
    #   #     memory: 20M      # 内存最大M
    ports:
      - "6379:6379"

networks:
  net-redis:
  net-node:
  net-mysql:
  net-nginx: